### ISSUE TITLE
Bilder werden nicht alle indexiert

### ISSUE THREAD

**Issue by bastians** [DMKEBUSINESSGMBH/typo3-mkdam2fal#3]
Ich komme leider nicht über den Step 1 hinaus, da nicht alle Bilder indexiert werden, mir fehlen 4. Kann ich da was tun? Setze ich den Haken bei Debug passiert auch nichts.

**Comment by darthnorman** [comment]
Das passiert manchmal. Meistens liegt es daran, dass Einträge zu Dateien in der Datenbank landen, die da nicht hingehören (z.B versteckte Dateien). Einfach mal in der Datenbank nachschauen (tx_dam Einträge bei denen damalreadyexported auf 0 steht) und ggf. mit diesem Statement von der Migrierung ausschließen:
`UPDATE tx_dam
SET deleted = 1
WHERE damalreadyexported = 0 AND deleted=0`

**Comment by bastians** [comment]
Danke, da waren genau vier Datensätze betroffen.

Habe danach bei Aufruf der Extension im Backend eine "Uncaught TYPO3 Exception" erhalten:

```
#1: PHP Warning: opendir([...]/typo3/mig/typo3temp/mkdam2fal/logs/): failed to open dir: No such file or directory in [...]/typo3/mig/typo3conf/ext/mkdam2fal/Classes/ServiceHelper/FileFolderRead.php line 87 (More information)

TYPO3\CMS\Core\Error\Exception thrown in file
[...]/typo3/mig/typo3/sysext/core/Classes/Error/ErrorHandler.php in line 101.
```

Ich habe die Extension dann deinstalliert und wieder installiert und nun passt es. Danke!
